### ISSUE TITLE
Fix check radio thick contrast

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/native-elements#128]
Use this snippet to adapt the tick color based on background color:

```css
.thick {
  background: inherit;
  background-clip: inherit;
  background-clip: text;
  color: transparent;
  filter: invert(1) grayscale(1) contrast(30);
}
```
