### ISSUE TITLE
ne-details: Fix middle details radius inside a group

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/native-elements#62]
Add a new condition to `ne-details`:

```css
@nest [ne-details-group] > &:not(:first-of-type, :last-of-type) {
    border-radius: 0;
}
```
